-- MySQL Script generated by MySQL Workbench
-- Thu Apr 23 18:20:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SistemaAcademiaBD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SistemaAcademiaBD` ;

-- -----------------------------------------------------
-- Schema SistemaAcademiaBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaAcademiaBD` ;
SHOW WARNINGS;
USE `SistemaAcademiaBD` ;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `Nascimento` DATE NOT NULL,
  `AtividadeFisica` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Tipousuario_idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idCliente_UNIQUE` ON `Cliente` (`idCliente` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT NOT NULL,
  `AtividadeFisica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPedido`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idPedido_UNIQUE` ON `Pedido` (`idPedido` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PersonalTrainer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PersonalTrainer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PersonalTrainer` (
  `idPersonalTrainer` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `Nascimento` DATE NOT NULL,
  `AtividadeFisica` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Tipousuario_idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idPersonalTrainer`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idPersonalTrainer_UNIQUE` ON `PersonalTrainer` (`idPersonalTrainer` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Servico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT NOT NULL,
  `PersonalTrainer_idPersonalTrainer` INT NOT NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  `AtividadeFisica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idServico`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idServico_UNIQUE` ON `Servico` (`idServico` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tipousuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tipousuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tipousuario` (
  `idTipoUsuario` INT NOT NULL,
  `TipoUsuariocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
