-- MySQL Script generated by MySQL Workbench
-- seg 27 abr 2020 09:23:57 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SistemaAcademiaBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SistemaAcademiaBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaAcademiaBD` ;
USE `SistemaAcademiaBD` ;

-- -----------------------------------------------------
-- Table `SistemaAcademiaBD`.`Tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaAcademiaBD`.`Tipousuario` (
  `idTipoUsuario` INT NOT NULL,
  `TipoUsuariocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaAcademiaBD`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaAcademiaBD`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `Nascimento` DATE NOT NULL,
  `AtividadeFisica` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Tipousuario_idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC),
  INDEX `fk_Cliente_Tipousuario1_idx` (`Tipousuario_idTipoUsuario` ASC),
  CONSTRAINT `fk_Cliente_Tipousuario1`
    FOREIGN KEY (`Tipousuario_idTipoUsuario`)
    REFERENCES `SistemaAcademiaBD`.`Tipousuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaAcademiaBD`.`PersonalTrainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaAcademiaBD`.`PersonalTrainer` (
  `idPersonalTrainer` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `Nascimento` DATE NOT NULL,
  `AtividadeFisica` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Tipousuario_idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idPersonalTrainer`),
  UNIQUE INDEX `idPersonalTrainer_UNIQUE` (`idPersonalTrainer` ASC),
  INDEX `fk_PersonalTrainer_Tipousuario1_idx` (`Tipousuario_idTipoUsuario` ASC),
  CONSTRAINT `fk_PersonalTrainer_Tipousuario1`
    FOREIGN KEY (`Tipousuario_idTipoUsuario`)
    REFERENCES `SistemaAcademiaBD`.`Tipousuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaAcademiaBD`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaAcademiaBD`.`Servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT NOT NULL,
  `PersonalTrainer_idPersonalTrainer` INT NOT NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  `AtividadeFisica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idServico`),
  UNIQUE INDEX `idServico_UNIQUE` (`idServico` ASC),
  INDEX `fk_Servico_Cliente_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Servico_PersonalTrainer1_idx` (`PersonalTrainer_idPersonalTrainer` ASC),
  CONSTRAINT `fk_Servico_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `SistemaAcademiaBD`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_PersonalTrainer1`
    FOREIGN KEY (`PersonalTrainer_idPersonalTrainer`)
    REFERENCES `SistemaAcademiaBD`.`PersonalTrainer` (`idPersonalTrainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaAcademiaBD`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaAcademiaBD`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT NOT NULL,
  `AtividadeFisica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPedido`),
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `SistemaAcademiaBD`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
